name: deploy-s3

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: JuliusKrause21/time-converter-ui
          run-id: ${{ github.event.workflow_run.id }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync dist s3://${{ secrets.BUCKET_NAME }} --delete